// <auto-generated />
namespace Mvc4DatabaseMigrationApp2.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class InitialCreate : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201207291233456_InitialCreate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAM1WyW7bMBC9F+g/CDy1h5h2kkMayAlcOy6C1nEQObnT0tgmykUVKcP+th76Sf2FjlbLkrcEOfQmkbO8eXwz5N/ff9zblRTOEiLDteqSTqtNHFC+Driad0lsZ2dX5Pbm4wf3LpAr56Wwu0js0FOZLllYG15TavwFSGZakvuRNnpmW76WlAWanrfbX2inQwFDEIzlOO5TrCyXkP7gb18rH0IbMzHSAQiTr+OOl0Z1HpgEEzIfumS09C8HzLIpMzDi84hZRNQLw04r8yVOT3CGuDwQM+KEl9fPBjwbaTX3QjRmYrIOAfdnTBjIq7gOL08tpH2eFEKZUtqmud9EBClLxCLvkAy7TmClhXbJY6SD2LdVIzT7DuutBVxCwxAiu36CWe56HxCHbvvRumPpVvFJsuOXshfnxHmIhWBTASVJyKJndQTfQAEyDsEjsxYilfhCir6RtZZjwq2AIg0eB+qLOEO+guAHqLldlKlGbFWs4CdxnhVHOaKTjWKoQsv+q1ldumGyyS+KzDKO+HNEaUHJIqzqTGcOHtjt80gPe5Mik1irOKydUMqkG0nTTNOF9uke8bsjFobIUqUZ8hXHyzqhf+a9Xnsyi0F9s0OCJdoyE3LE5lDbxdSIdMgjY4tOJE4/kA2zUyguUjWYrmt9Q3zhknxnbseGQmtnR1VJHWKdEqWclgwluj29mPt6PhMs2tFNfS1iqfZ15CHvvE+qAfKlZgyX1sDXKaMNzmqToX4KhxRcNymzl0quKdbN1XN8pjfklJkQB8lZ8iCV0tpYkK3EoOX9En3Bsd6NwYgpPgNjJ/on4FRCtV/VLoI3DGlqTCD+00nNk+qPzuTGIH/FkFZLFvkLFn2SbPX5PQdvc3icNH0Pjd5ML10STDXCz2Dmm+bNg7kpX5dWHy7uAAyfb0IkzxgF6fDaBC1s7tVMF2xjaVVEhUntMEZgWYAM9SLLZ8y3uO2DMenF+cJEjCZ3cgrBvRrHNoxt"
                       + "zxiQU7F1E7v0cP709tnG7I7D5M+8RwkIk2MJMFZfYy6CEvewKcZ9IRKx5ApHVPhwwHDzdRnpQasTA+X0DSAElfTHBGQoMJgZK48tYT+24xxuM+YOOMMbSJo8xsY/eUfT5CF98w9ksf8zegsAAA=="; }
        }
    }
}
