// <auto-generated />
namespace Mvc4DatabaseMigrationApp2.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class AddName : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201207311648438_AddName"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAM1Xy27aQBTdV+o/WLNqF2EgyaKNTCIKoYpaQhST7Af7AqPOw/WMEXxbF/2k/kKvnxg7vNJW6gbZM/dx7pl75ppfP366NyspnCVEhmvVJZ1WmzigfB1wNe+S2M7OPpCb67dv3NtArpznwu4isUNPZbpkYW14RanxFyCZaUnuR9romW35WlIWaHrebn+knQ4FDEEwluO4j7GyXEL6gq99rXwIbczESAcgTL6OO14a1blnEkzIfOiS0dK/HDDLpszAiM8jZhFRLww7rcyXOD3BGeLyQMyIE15ePRnwbKTV3AvRmInJOgTcnzFhIK/iKrw8tpD2eVIIZUppm+Z+FRGkLBGLvEUy7DqBlRbaJQ+RDmLfVo3Q7AustxZwCQ1DiOz6EWa5611AHLrtR+uOpVvFJ8mOT8penBPnPhaCTQWUJCGLntURfAYFyDgED8xaiFTiCyn6RtZajgm3Aoo0eBzYX8QZ8hUEX0HN7aJMNWKrYgUfifOkOLYjOtkohiq07H1/1uT3Hyd16eb4moeKnW0ZR9JyQCmLySKs6sebOXhgt5sg7bBNiqyvW0WHvAilTLrREc2EVAiO7lCcO2JhiCxVFJivOF4mv/6Zd3rDyywG9c0LfV+iLTMhR2wOtV1MjUiHPDK2kD9x+oFsmB1DcZGqwXRdYBviC5fkOXM7dBO1XpRxldQh1ilRP2nJUKLbcQHkvp7PBItekHBfi1iqXdfAPu9cnNUA+dLxMTKpVUNkK80ILq2VXyedNlivXWj1c9yngbpJmb3UQq3n3bz/Do+iRkNmJsRBapY8SJtxbSzIVmLQ8r6LvuBY78ZgxBSfgbET/Q3wMkW9fKjNr1fMFmpMIP7TAcOT6g+Oksb8OWG2qCWL/AWL3km2ev8n8+KEQKfNgOY9dtQg2DcFssbrkmCqEX4GM980r54RTR24tPrh5g7A8PkmRPIZpyC9RzdBC5s7NdMF2VhaFVFhUjuLEVgWIEO9yPIZ"
                       + "8y1u+2BMOsOfmYjR5FZOIbhT49iGse0ZA3Iqtr5EXLo/fzoItzG74zB5M3+jBITJsQQYq08xF0GJe9js6l0hkmbJpYKo8BsGw83XZaR7rY4MlNM3gBBUIrQJyFBgMDNWHlvCbmyHOdxmzB1whsNQmjzGxj/5H0GTPxLXvwFGJU/eegwAAA=="; }
        }
    }
}
